import { useEffect, useState } from "react";
import { rpc, mediaUrl, type ProjectSummary } from "../lib/rpc";

type Doc = {document_id:string;document_key:string;title:string;kind:string;head_revision_id:string;approved_revision_id:string|null;needs_review:number;volume_order:number;chapter_order:number};
type Revision = {revision_id:string;asset_version_id:string;parent_revision_id?:string;created_at:string;body?:string};
type Detail = Doc & {revision:Revision};
type Source = {reference_id:string;title:string;media_type:string;pin_mode:string;asset_version_id:string};
type Exported = {asset_version_id:string;format:string;chapters:{title:string}[]};
const kinds:Record<string,string>={bible:"共享设定",character:"角色",timeline:"时间线",foreshadow:"伏笔",volume:"卷纲",chapter:"章节",review:"审稿",adaptation:"动画映射"};
const button="rounded border border-border-subtle bg-bg-raise2 px-3 py-2 text-sm hover:bg-bg-hover disabled:opacity-50";
const field="w-full rounded border border-border-subtle bg-bg-raise2 px-3 py-2 text-text-primary";
const empty=()=>({document_key:"",kind:"chapter",title:"",body:"",volume_order:1,chapter_order:1});

export default function NovelPage(){
  const [projects,setProjects]=useState<ProjectSummary[]>([]),[project,setProject]=useState("");
  const [docs,setDocs]=useState<Doc[]>([]),[selected,setSelected]=useState<Detail|null>(null),[form,setForm]=useState(empty);
  const [history,setHistory]=useState<Revision[]>([]),[sources,setSources]=useState<Source[]>([]),[referenceIds,setReferenceIds]=useState<string[]>([]);
  const [snapshot,setSnapshot]=useState<string|null>(null),[busy,setBusy]=useState(false),[notice,setNotice]=useState(""),[error,setError]=useState("");
  const [panel,setPanel]=useState<"history"|"context"|"mapping"|"model">("history"),[output,setOutput]=useState<unknown>(null),[download,setDownload]=useState<Exported|null>(null);
  const [instruction,setInstruction]=useState(""),[jobKey,setJobKey]=useState(""),[jobId,setJobId]=useState("");
  const [mapping,setMapping]=useState({scene_goal:"",motivation:"",causality:"",emotion:"",boundaries:"",visible_action:"",dialogue:""});
  const [mapTitle,setMapTitle]=useState(""),[mapKey,setMapKey]=useState("");
  const [dirty,setDirty]=useState(false);
  const call=<T,>(domain:string,access:"read"|"write",params:Record<string,unknown>)=>rpc<T>("novel."+domain+"."+access,{project_id:project,...params});
  async function run(action:()=>Promise<void>){setBusy(true);setError("");try{await action();}catch(e){setError(e instanceof Error?e.message:String(e));}finally{setBusy(false);}}
  const leave=()=>!dirty||window.confirm("当前修改未保存，是否离开？");
  async function refresh(){setDocs(await call<Doc[]>("document","read",{op:"list",limit:1000}));}
  async function open(d:{document_id:string}){const detail=await call<Detail>("document","read",{op:"get",document_id:d.document_id});setSelected(detail);setForm({document_key:detail.document_key,kind:detail.kind,title:detail.title,body:detail.revision.body??"",volume_order:detail.volume_order,chapter_order:detail.chapter_order});setHistory(await call<Revision[]>("document","read",{op:"history",document_id:d.document_id}));setDirty(false);setOutput(null);setDownload(null);}
  useEffect(()=>{void rpc<ProjectSummary[]>("project.search",{limit:200}).then(setProjects).catch(e=>setError(String(e)));},[]);
  useEffect(()=>{setSelected(null);setForm(empty());setHistory([]);setSnapshot(null);setSources([]);setReferenceIds([]);setOutput(null);setDirty(false);if(project)void run(async()=>{await refresh();setSources(await call<Source[]>("workflow","read",{op:"sources"}));});else setDocs([]);},[project]);
  const edit=(patch:Partial<ReturnType<typeof empty>>)=>{setForm(old=>({...old,...patch}));setDirty(true);};
  const target=selected?{document_id:selected.document_id}: {document_key:form.document_key};
  async function save(){
    const result=await call<{document_id:string}>("document","write",{op:"save",...form,expected_head:selected?.head_revision_id??null,...(snapshot && form.kind==="chapter"?{snapshot_id:snapshot}:{})});
    await refresh();await open({document_id:result.document_id});setNotice("草稿已保存，历史版本保留。");
  }
  async function decide(op:"approve"|"reject"){
    if(!selected)return;
    setOutput(await call("document","write",{op,document_id:selected.document_id,revision_id:selected.head_revision_id,expected_head:selected.head_revision_id}));
    await refresh();await open(selected);setNotice(op==="approve"?"版本已审定并固定项目引用。":"已标记需复查，旧审定版本保持。");
  }
  return <div className="flex h-full min-h-0 flex-col gap-4 overflow-auto p-5">
    <header className="flex flex-wrap items-center justify-between gap-3"><div><h1 className="text-xl font-semibold">小说工作台</h1><p className="mt-1 text-sm text-text-secondary">共享设定 · 分卷章节 · 版本审定 · 动画交接</p></div><label className="flex items-center gap-2 text-sm">项目<select aria-label="小说项目" className={field} value={project} onChange={e=>{if(leave())setProject(e.target.value);}}><option value="">选择已有项目</option>{projects.map(p=><option value={p.project_id} key={p.project_id}>{p.title}</option>)}</select></label></header>
    {error&&<div role="alert" className="rounded border border-red-500/50 bg-red-500/10 p-3 text-sm">{error}</div>}
    {notice&&<div role="status" className="text-sm text-accent">{notice}</div>}
    {!project?<div className="rounded border border-border-subtle p-8 text-text-secondary">选择项目后，建立共享设定、卷纲与章节。小说和动画使用同一项目的素材。</div>:<div className="grid min-h-0 flex-1 gap-4 xl:grid-cols-[220px_minmax(300px,1fr)_360px]">
      <aside className="space-y-3 rounded border border-border-subtle p-3"><button className={button+" w-full"} disabled={busy} onClick={()=>{if(leave()){setSelected(null);setForm(empty());setDirty(false);setHistory([]);}}}>新建文档</button><div className="space-y-2">{docs.map(d=><button key={d.document_id} className={button+" w-full text-left "+(selected?.document_id===d.document_id?"text-accent":"")} disabled={busy} onClick={()=>{if(leave())void run(()=>open(d));}}><span className="block font-medium">{d.title}</span><span className="block text-xs text-text-secondary">{kinds[d.kind]} · {d.needs_review?"需复查":d.head_revision_id===d.approved_revision_id?"已审定":"草稿"}</span></button>)}{!docs.length&&<p className="text-sm text-text-secondary">本项目还没有叙事文档。</p>}</div></aside>
      <section className="flex min-h-[500px] flex-col gap-3 rounded border border-border-subtle p-4">
        <div className="grid gap-3 sm:grid-cols-2"><label className="text-sm">标题<input aria-label="文档标题" className={field} value={form.title} onChange={e=>edit({title:e.target.value})}/></label><label className="text-sm">文档标识<input aria-label="文档标识" className={field} value={form.document_key} disabled={!!selected} placeholder="如 chapter:1" onChange={e=>edit({document_key:e.target.value})}/></label><label className="text-sm">类型<select aria-label="文档类型" className={field} value={form.kind} disabled={!!selected} onChange={e=>edit({kind:e.target.value})}>{Object.entries(kinds).filter(([k])=>k!=="adaptation").map(([k,v])=><option key={k} value={k}>{v}</option>)}{form.kind==="adaptation"&&<option value="adaptation">动画映射</option>}</select></label><div className="grid grid-cols-2 gap-2">{(["volume_order","chapter_order"] as const).map((key,i)=><label key={key} className="text-sm">{i?"章序":"卷序"}<input aria-label={i?"章序":"卷序"} type="number" min="0" className={field} value={form[key]} onChange={e=>edit({[key]:Number(e.target.value)})}/></label>)}</div></div>
        <label className="flex flex-1 flex-col gap-2 text-sm">正文<textarea aria-label="小说正文" className={field+" min-h-[280px] flex-1 resize-y font-mono leading-7"} value={form.body} disabled={form.kind==="adaptation"} onChange={e=>edit({body:e.target.value})}/></label>
        <div className="flex flex-wrap gap-2"><button className={button+" text-accent"} disabled={busy||form.kind==="adaptation"} onClick={()=>void run(save)}>保存草稿</button><button className={button} disabled={busy||!selected||dirty} onClick={()=>void run(()=>decide("approve"))}>审定当前版本</button><button className={button} disabled={busy||!selected||dirty} onClick={()=>void run(()=>decide("reject"))}>标记需复查</button><button className={button} disabled={busy||!selected} onClick={()=>void run(async()=>{setOutput(await call("workflow","read",{op:"impact",revision_id:selected?.approved_revision_id??selected?.head_revision_id}));})}>改稿影响</button></div>
        <div className="flex flex-wrap items-center gap-2 border-t border-border-subtle pt-3"><span className="text-xs text-text-secondary">导出审定章节</span>{(["txt","md","epub"] as const).map(format=><button key={format} className={button} disabled={busy} onClick={()=>void run(async()=>{setDownload(await call<Exported>("workflow","write",{op:"export",format}));setNotice("导出已登记到项目素材。");})}>{format.toUpperCase()}</button>)}{download&&<a className="text-sm text-accent underline" href={mediaUrl.file(download.asset_version_id)} download>下载 {download.format.toUpperCase()}</a>}</div>
      </section>
      <aside className="space-y-4 rounded border border-border-subtle p-3"><div className="flex flex-wrap gap-1">{(["history","context","mapping","model"] as const).map((p,i)=><button key={p} className={button+(panel===p?" text-accent":"")} onClick={()=>setPanel(p)}>{["版本","上下文","动画","模型"][i]}</button>)}</div>
        {panel==="history"&&<section className="space-y-3"><h2 className="font-medium">版本记录</h2>{history.map(r=><div key={r.revision_id} className="rounded border border-border-subtle p-2 text-xs"><div>{r.created_at}</div><div className="mt-1 break-all text-text-secondary">{r.revision_id}</div><button className={button+" mt-2"} disabled={busy} onClick={()=>void run(async()=>{setOutput(await call("document","read",{op:"diff",...target,from_revision_id:r.revision_id,to_revision_id:selected?.head_revision_id}));})}>与当前稿对照</button></div>)}{!history.length&&<p className="text-sm text-text-secondary">保存后可查看历史版本与差异。</p>}</section>}
        {panel==="context"&&<section className="space-y-3"><h2 className="font-medium">章级上下文</h2><p className="text-sm text-text-secondary">已审定设定必选；项目资源作为参考，不自动成为设定。</p>{sources.map(s=><label key={s.reference_id} className="flex gap-2 text-sm"><input type="checkbox" checked={referenceIds.includes(s.reference_id)} onChange={e=>setReferenceIds(ids=>e.target.checked?[...ids,s.reference_id]:ids.filter(id=>id!==s.reference_id))}/><span>{s.title}<small className="block text-text-faint">{s.media_type} · {s.pin_mode}</small></span></label>)}<button className={button} disabled={busy} onClick={()=>void run(async()=>{const result=await call<{snapshot_id:string}>("workflow","write",{op:"context",reference_ids:referenceIds});setSnapshot(result.snapshot_id);setOutput(result);setNotice("上下文已固定；后续设定变更会要求复查。");})}>固定上下文</button><p className="break-all text-xs text-text-secondary">{snapshot?"当前快照："+snapshot:"尚未固定上下文"}</p></section>}
        {panel==="mapping"&&<section className="space-y-3"><h2 className="font-medium">小说—动画交接</h2><p className="text-sm text-text-secondary">先选择审定章节，并在上下文页固定设定。</p><label className="block text-sm">场次标题<input className={field} value={mapTitle} onChange={e=>setMapTitle(e.target.value)}/></label><label className="block text-sm">映射标识<input className={field} value={mapKey} placeholder="如 adaptation:1" onChange={e=>setMapKey(e.target.value)}/></label>{Object.entries({scene_goal:"场次目标",motivation:"人物动机",causality:"因果",emotion:"情绪节点",boundaries:"不可丢边界",visible_action:"可视动作",dialogue:"对白"}).map(([key,label])=><label className="block text-sm" key={key}>{label}<textarea className={field} value={mapping[key as keyof typeof mapping]} onChange={e=>setMapping(m=>({...m,[key]:e.target.value}))}/></label>)}<button className={button} disabled={busy||!selected||!snapshot} onClick={()=>void run(async()=>{setOutput(await call("adaptation","write",{op:"save",document_key:mapKey,title:mapTitle,expected_head:null,chapter_revision_id:selected?.approved_revision_id,snapshot_id:snapshot,mapping}));await refresh();setNotice("映射草稿已保存；选择它后审定并交接。");})}>保存动画映射</button><button className={button} disabled={busy||selected?.kind!=="adaptation"} onClick={()=>void run(async()=>setOutput(await call("adaptation","read",{op:"handoff",...target})))}>读取审定交接包</button></section>}
        {panel==="model"&&<section className="space-y-3"><h2 className="font-medium">独立文本模型</h2><p className="text-sm text-text-secondary">付费执行默认关闭。配置模型和预算后，模型结果先进入任务，再合入草稿，不自动审定。</p><label className="block text-sm">写作要求<textarea className={field} value={instruction} onChange={e=>setInstruction(e.target.value)}/></label><label className="block text-sm">任务标识<input className={field} value={jobKey} onChange={e=>setJobKey(e.target.value)}/></label><button className={button} disabled={busy||!snapshot} onClick={()=>void run(async()=>setOutput(await call("generation","read",{op:"plan",snapshot_id:snapshot,instruction})))}>查看执行计划</button><button className={button} disabled={busy||!snapshot||dirty} onClick={()=>{if(window.confirm("确认按已配置的独立模型预算执行？未启用付费时不会调用模型。"))void run(async()=>{const job=await call<{job_id:string}>("generation","write",{op:"execute",job_key:jobKey,snapshot_id:snapshot,instruction,document_key:form.document_key,title:form.title,kind:form.kind,expected_head:selected?.head_revision_id??null,accept_cost:true});setJobId(job.job_id);setOutput(job);});}}>执行模型任务</button><button className={button} disabled={busy||!jobId} onClick={()=>void run(async()=>{setOutput(await call("generation","write",{op:"commit",job_id:jobId}));await refresh();})}>结果合入草稿</button><button className={button} disabled={busy} onClick={()=>void run(async()=>setOutput(await call("generation","read",{op:"list"})))}>任务与用量记录</button></section>}
        {output!==null&&<details open className="border-t border-border-subtle pt-3"><summary className="text-sm">操作结果</summary><pre className="mt-2 max-h-[480px] overflow-auto whitespace-pre-wrap break-all text-xs text-text-secondary">{JSON.stringify(output,null,2)}</pre></details>}
      </aside>
    </div>}
    {busy&&<span role="status" className="text-sm text-text-secondary">正在处理…</span>}
  </div>;
}
